### PR TITLE
Write logs before sending result to the channel

### LINKED ISSUE #116: Missing or incomplete logs from runConfigHook()
Sometimes the log for the end of the pre_promote hook `Hook END                                 porter_version=v2.4.1 cmd=build-promote HookName=pre_promote` appears before logs for individual hooks are shown. If an error happens in the configHook, the run will stop but no error is shown in the log.

### PR DESCRIPTION
**Pull request by linxia**
## Changelog

fix missing or incomplete hook logs
## Issues fixed or closed

Fixes #116
## Questions (open the PR then click the check boxes)

Did you update the documentation related to your changes?
- [x] Yes
- [ ] My changes were not already documented

Did you run `make` _before_ committing code and opening this PR?
- [x] Yes
- [ ] I didn't change any code

Did you run `porter create-stack` and `porter sync-stack` to verify provisioning
works?
- [ ] Yes
- [x] N/A

### CODE REVIEW

**Comment by linxia** [comment]
@phylake please review

**Comment by phylake** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/117/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Comment by phylake** [comment]
@jfieber or @davepersing please take a look

**Comment by davepersing** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/117/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Pull request merged**
