### PR TITLE
cis benchmark remediations

### LINKED ISSUE #42: CIS Docker 1.11 - 2.13 Disable operations on legacy registry

### LINKED ISSUE #55: CIS Docker 1.11 - 5.12 Mount container's root filesystem as read only

### LINKED ISSUE #56: CIS Docker 1.11 - 5.14 Set the 'on-failure' container restart policy to 5

### PR DESCRIPTION
**Pull request by phylake**
## Changelog

CIS Docker benchmark 1.11.0 remediations
## Issues fixed or closed

Closes #42 
Closes #55 
Closes #56 
## Questions (open the PR then click the check boxes)

Did you update the documentation related to your changes?
- [x] Yes
- [ ] My changes were not already documented

Did you run `make` _before_ committing code and opening this PR?
- [x] Yes
- [ ] I didn't change any code

Did you run `porter create-stack` and `porter sync-stack` to verify provisioning
works?
- [x] Yes
- [ ] N/A

### CODE REVIEW

**Comment by phylake** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/57/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Comment by gregoryfischer** [comment]
👍

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/57/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Comment by davepersing** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/57/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Pull request merged**
