### PR TITLE
Stats auth

### PR DESCRIPTION
**Pull request by phylake**
## Changelog

- variable HAProxy stats auth
- updated sample project

## Questions (open the PR then click the check boxes)

Did you update the documentation related to your changes?

- [x] Yes
- [ ] My changes were not already documented

Did you run `make` _before_ committing code and opening this PR?

- [x] Yes
- [ ] I didn't change any code

Did you run `porter create-stack` and `porter sync-stack` to verify provisioning
works?

- [x] Yes
- [ ] N/A

### CODE REVIEW

**Comment by phylake** [comment]
The updates to the sample project are unrelated to the HAProxy changes just didn't want to create PR noise. Also, this isn't a breaking change for hooks that correctly integrated with porter in the first place by using [environment variables](https://github.com/adobe-platform/porter/blob/master/docs/detailed_design/deployment-hooks.md#standard-environment-variables)

**Comment by phylake** [comment]
That is, ASR/opscode copy/pasted [these values](https://github.com/adobe-platform/porter/blob/40ffe13f2aedbebca8c3c72cd69af575edd9b55c/constants/constants.go#L83-L84)

**Review by davepersing — APPROVED** [review]

**Comment by gregoryfischer** [comment]
👍

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/162/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Comment by phylake** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/162/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Pull request merged**
