### PR TITLE
Hook env

### LINKED ISSUE #31: Optionally run hooks concurrently

### PR DESCRIPTION
**Pull request by phylake**
## Changelog

This will be part of porter v2
- fixed config validation failure producing a false positive of success
- improved hook environment variable injection to match Docker Compose
- got rid of hardcoded `.porter/hooks/` and made path to hooks configurable
- tweaked config validation so config can be created dynamically in pre_pack
- enabled deployment hooks to run concurrently
## Issues fixed or closed

Closes #31 
## Questions (open the PR then click the check boxes)

Did you update the documentation related to your changes?
- [x] Yes
- [ ] My changes were not already documented

Did you run `make` _before_ committing code and opening this PR?
- [x] Yes
- [ ] I didn't change any code

Did you run `porter create-stack` and `porter sync-stack` to verify provisioning
works?
- [ ] Yes
- [x] N/A

### CODE REVIEW

**Comment by phylake** [comment]
👍

**Comment by phylake** [comment]
👍

**Comment by davepersing** [comment]
👍

**Comment by gregoryfischer** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/51/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Comment by phylake** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/51/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Pull request merged**
