### PR TITLE
Allows SELINUX hosts to share content on mounts with the container

### PR DESCRIPTION
**Pull request by ssvaddiparthy**
## Changelog

Fill this in and update CHANGELOG.md

## Questions (open the PR then click the check boxes)

Did you update the documentation related to your changes?

- [x] Yes
- [ ] My changes were not already documented

Did you run `make` _before_ committing code and opening this PR?

- [x] Yes
- [ ] I didn't change any code

Did you run `porter create-stack` and `porter sync-stack` to verify provisioning
works?

- [x] Yes
- [ ] N/A

### CODE REVIEW

**Comment by phylake** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/181/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Comment by cdmurph32** [comment]
I've confirmed this fix with Background Removal.

**Comment by cdmurph32** [comment]
@vsandeepsrivastav You can check the yes boxes above. Or someone else with write privileges can.

**Comment by cdmurph32** [comment]
Version 4.8.1:
```
Running deployment hook START
=============================
Traceback (most recent call last):
  File "/BuildCustomVPCStack.py", line 83, in <module>
    logging.basicConfig(level=logging.INFO, filename="buildcustomvpcstack.log")
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/repo_root/buildcustomvpcstack.log'
```
With change:
```
Running deployment hook START
=============================
===========================
Running deployment hook END
t=2017-06-07T21:51:54+0000 lvl=dbug msg="buildAndRun() END" porter_version=vCOLMURPH cmd=pack HookName=pre_pack HookIndex=0 Concurrent=false Repo=git@git.corp.adobe.com:EchoSign/BuildCustomVPCStack.git Ref=0.1 RunCondition=pass Dockerfile=.porter-tmp/pre_pack_clone_0_1/pre-pack ImageName=backgroundremoval-pre_pack-0-1
```

**Comment by phylake** [comment]
@davepersing can you take a look too?

**Comment by davepersing** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/181/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Pull request merged**
