### PR TITLE
test environment

### PR DESCRIPTION
**Pull request by phylake**
## Changelog
- incorporated disposable/repeatable test infrastructure
- fixed hook logic
## Questions (open the PR then click the check boxes)

Did you update the documentation related to your changes?
- [ ] Yes
- [x] My changes were not already documented

Did you run `make` _before_ committing code and opening this PR?
- [x] Yes
- [ ] I didn't change any code

Did you run `porter create-stack` and `porter sync-stack` to verify provisioning
works?
- [ ] Yes
- [x] N/A

### CODE REVIEW

**Comment by phylake** [comment]
@cdmurph32 Pull Approve got into a bad state when i removed the collaborators thinking all i needed was Pull Approve status checks. Can i get a 👍  please?

**Comment by gregoryfischer** [comment]
👍

**Comment by phylake** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/adobe-platform/porter/pull-request/54/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=adobe-platform/porter)

**Comment by phylake** [comment]
Pull Approve got all messed up i was able to force a merge

**Pull request merged**
